# Generated by Django 5.2 on 2025-08-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'يرجى إدخال جهة العمل'}, max_length=100, verbose_name='جهة العمل')),
            ],
            options={
                'verbose_name': 'جهة العمل',
                'verbose_name_plural': 'جهات العمل',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'يرجى إدخال الاسم'}, max_length=255, verbose_name='الاسم')),
                ('rank', models.CharField(choices=[('ملازم', 'ملازم'), ('ملازم أول', 'ملازم أول'), ('نقيب', 'نقيب'), ('رائد', 'رائد'), ('مقدم', 'مقدم'), ('عقيد', 'عقيد'), ('عميد', 'عميد'), ('لواء', 'لواء'), ('لواء مساعد وزير', 'لواء مساعد وزير')], error_messages={'blank': 'يرجى إدخال الرتبة'}, max_length=16, verbose_name='الرتبة')),
                ('national_id', models.CharField(error_messages={'blank': 'يرجى إدخال الرقم القومي', 'unique': 'الرقم القومي مستخدم من قبل'}, max_length=14, unique=True, verbose_name='الرقم القومي')),
                ('birth_date', models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح'}, verbose_name='تاريخ الميلاد')),
                ('age', models.PositiveIntegerField(error_messages={'invalid': 'يرجى إدخال السن'}, verbose_name='السن')),
                ('hire_date', models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صحيح'}, verbose_name='تاريخ التعيين')),
                ('phone_number', models.CharField(error_messages={'blank': 'يرجى إدخال رقم الهاتف'}, max_length=15, verbose_name='رقم الهاتف')),
                ('membership_type', models.CharField(choices=[('مؤسس', 'مؤسس'), ('عامل', 'عامل'), ('منضم', 'منضم')], default='منضم', max_length=10, verbose_name='نوع العضوية')),
                ('membership_number', models.CharField(error_messages={'blank': 'يرجى إدخال رقم العضوية', 'unique': 'رقم العضوية مستخدم مسبقًا'}, max_length=20, unique=True, verbose_name='رقم العضوية')),
                ('subscription_date', models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صحيح'}, verbose_name='تاريخ الاشتراك')),
                ('marital_status', models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('أرمل', 'أرمل')], max_length=10, verbose_name='الحالة الاجتماعية')),
                ('graduation_year', models.PositiveIntegerField(error_messages={'invalid': 'يرجى إدخال سنة التخرج'}, verbose_name='سنة التخرج')),
                ('class_rank', models.CharField(error_messages={'blank': 'يرجى إدخال الترتيب'}, max_length=50, verbose_name='الترتيب على الدفعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('work_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.workentity', verbose_name='جهة العمل')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
    ]
