# Generated by Django 5.2 on 2025-08-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(error_messages={'blank': 'يرجى إدخال رقم الهاتف', 'unique': 'رقم الهاتف مستخدم من قبل'}, max_length=15, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
