# Generated by Django 5.2 on 2025-08-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='work_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='clients.workentity', verbose_name='جهة العمل'),
        ),
    ]
