# Generated by Django 5.2 on 2025-08-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_work_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
    ]
