# Generated by Django 5.2 on 2025-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=1, error_messages={'invalid': 'يرجى إدخال قيمة مالية صحيحة'}, max_digits=12, verbose_name='المبلغ المدفوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=1, error_messages={'invalid': 'يرجى إدخال قيمة مالية صحيحة'}, help_text='القيمة الإجمالية لرسوم اشتراك العضو', max_digits=12, verbose_name='رسوم الاشتراك'),
            preserve_default=False,
        ),
    ]
