# Generated by Django 5.2 on 2025-08-24 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_paid_amount_client_subscription_fee'),
        ('financials', '0011_alter_installment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='financial_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='financials.financialrecord', verbose_name='المدفوع مقدما'),
        ),
    ]
