# Generated by Django 5.2 on 2025-09-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_financial_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='client',
            name='residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محل الإقامة'),
        ),
    ]
