# Generated by Django 5.2 on 2025-09-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_client_hire_date_client_residence'),
        ('financials', '0014_alter_installment_financial_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='financial_record',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='client',
            name='prepaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='financials.financialrecord', verbose_name='المدفوع مقدما'),
        ),
    ]
