# Generated by Django 5.2 on 2025-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_client_financial_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='membership_number',
            field=models.IntegerField(error_messages={'blank': 'يرجى إدخال رقم العضوية', 'unique': 'رقم العضوية مستخدم مسبقًا'}, unique=True, verbose_name='رقم العضوية'),
        ),
    ]
