# Generated by Django 5.2 on 2025-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_client_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prepaid_amount_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المدفوع مقدما (مؤقت)'),
        ),
    ]
