# Generated by Django 5.2 on 2025-10-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_prepaid_amount_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='prepaid',
        ),
    ]
