# Generated by Django 5.2 on 2025-10-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_client_prepaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='prepaid_amount_temp',
            new_name='prepaid',
        ),
    ]
