fieldLabels = {
    "rank": "الرتبة",
    "name": "الاسم",
    "membership_number": "رقم العضوية",
    "seniority": "الأقدمية",
    "subscription_date": "تاريخ الاشتراك",
    "work_entity": "جهة العمل",
    "age": "العمر",
    "national_id": "الرقم القومي",
    "birth_date": "تاريخ الميلاد",
    "residence": "محل الإقامة",
    "phone_number": "رقم الهاتف",
    "membership_type": "نوع العضوية",
    "marital_status": "الحالة الاجتماعية",
    "graduation_year": "سنة التخرج",
    "class_rank": "الترتيب على الدفعة",
    "notes": "ملاحظات",
    "is_active": "الحالة",
    "created_at": "تاريخ الإنشاء",
    "created_by": "تم الإنشاء بواسطة",
};
