# Generated by Django 5.2 on 2025-08-25 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل اسم المشروع', max_length=255, verbose_name='اسم المشروع')),
                ('start_date', models.DateField(help_text='تاريخ بداية المشروع', verbose_name='تاريخ البداية')),
                ('status', models.CharField(choices=[('قيد التنفيذ', 'قيد التنفيذ'), ('منتهي', 'منتهي')], default='قيد التنفيذ', help_text='حالة المشروع', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
            },
        ),
    ]
