# Generated by Django 5.2 on 2025-08-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_alter_installment_client'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(error_messages={'blank': 'يجب إدخال البيان', 'null': 'يجب إدخال البيان'}, max_length=255, verbose_name='البيان')),
                ('financial_record', models.ForeignKey(error_messages={'blank': 'يجب ربط العملية بمعاملة مالية', 'null': 'يجب ربط العملية بمعاملة مالية'}, on_delete=django.db.models.deletion.RESTRICT, related_name='project_transactions', to='financials.financialrecord', verbose_name='المعاملة المالية')),
                ('project', models.ForeignKey(error_messages={'blank': 'يجب ربط العملية بمشروع', 'null': 'يجب ربط العملية بمشروع'}, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'عملية مشروع',
                'verbose_name_plural': 'عمليات المشاريع',
            },
        ),
    ]
