# Generated by Django 5.2 on 2025-08-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_alter_installment_client'),
        ('projects', '0002_projecttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttransaction',
            name='financial_record',
            field=models.ForeignKey(error_messages={'blank': 'يجب ربط العملية بمعاملة مالية', 'null': 'يجب ربط العملية بمعاملة مالية'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='financials.financialrecord', verbose_name='المعاملة المالية'),
        ),
    ]
