# Generated by Django 5.2 on 2025-09-08 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_alter_financialrecord_payment_method'),
        ('projects', '0003_alter_projecttransaction_financial_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttransaction',
            name='financial_record',
            field=models.OneToOneField(error_messages={'blank': 'يجب ربط العملية بمعاملة مالية', 'null': 'يجب ربط العملية بمعاملة مالية'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_transaction', to='financials.financialrecord', verbose_name='المعاملة المالية'),
        ),
    ]
