# Generated by Django 5.2 on 2025-08-16 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'يرجى إدخال اسم الحساب البنكي', 'null': 'اسم الحساب البنكي لا يمكن أن يكون فارغًا', 'unique': 'اسم الحساب البنكي موجود بالفعل'}, max_length=255, unique=True, verbose_name='اسم الحساب البنكي')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'يرجى إدخال اسم نوع المعاملة', 'null': 'اسم نوع المعاملة لا يمكن أن يكون فارغًا'}, max_length=255, verbose_name='اسم نوع المعاملة')),
                ('type', models.CharField(choices=[('إيراد', 'إيراد'), ('مصروف', 'مصروف')], error_messages={'blank': 'يرجى تحديد النوع', 'invalid_choice': 'يرجى اختيار نوع صحيح (إيراد أو مصروف)'}, max_length=10, verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'نوع معاملة',
                'verbose_name_plural': 'أنواع المعاملات',
                'ordering': ['type', 'name'],
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, error_messages={'blank': 'يرجى إدخال المبلغ', 'invalid': 'يرجى إدخال قيمة رقمية صحيحة', 'null': 'المبلغ لا يمكن أن يكون فارغًا'}, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(error_messages={'blank': 'يرجى إدخال التاريخ', 'invalid': 'يرجى إدخال تاريخ صحيح', 'null': 'التاريخ لا يمكن أن يكون فارغًا'}, verbose_name='التاريخ')),
                ('payment_method', models.CharField(choices=[('نقدي', 'نقدي'), ('إيصال بنكي', 'إيصال بنكي')], error_messages={'blank': 'طريقة الدفع مطلوبة', 'invalid_choice': 'يرجى اختيار طريقة دفع صحيحة'}, max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financials.bankaccount', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('transaction_type', models.ForeignKey(error_messages={'invalid': 'يرجى اختيار نوع معاملة صحيح', 'null': 'نوع المعاملة مطلوب'}, on_delete=django.db.models.deletion.RESTRICT, to='financials.transactiontype', verbose_name='نوع المعاملة')),
            ],
            options={
                'verbose_name': 'سجل مالي',
                'verbose_name_plural': 'السجلات المالية',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
