# Generated by Django 5.2 on 2025-08-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإيصال'),
        ),
    ]
