# Generated by Django 5.2 on 2025-08-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_financialrecord_receipt_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'حساب بنكي', 'verbose_name_plural': 'الحسابات البنكية'},
        ),
    ]
