# Generated by Django 5.2 on 2025-08-18 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_alter_bankaccount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, error_messages={'invalid': 'يرجى إدخال قيمة مالية صحيحة'}, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(error_messages={'invalid': 'أدخل تاريخ صالح'}, verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('مدفوع', 'مدفوع'), ('غير مدفوع', 'غير مدفوع')], default='غير مدفوع', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('paid_at', models.DateField(blank=True, error_messages={'invalid': 'أدخل تاريخ صالح'}, null=True, verbose_name='تاريخ الدفع')),
                ('transaction', models.ForeignKey(error_messages={'blank': 'يجب تحديد المعاملة المالية', 'null': 'يجب ربط الاشتراك بمعاملة مالية'}, on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='financials.financialrecord', verbose_name='المعاملة المالية')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-date'],
            },
        ),
    ]
