# Generated by Django 5.2 on 2025-08-18 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_notes'),
        ('financials', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(default=1, error_messages={'blank': 'يجب تحديد المعاملة المالية', 'null': 'يجب ربط الاشتراك بمعاملة مالية'}, on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='clients.client', verbose_name='العضو'),
            preserve_default=False,
        ),
    ]
