# Generated by Django 5.2 on 2025-08-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_subscription_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('ملازم', 'ملازم'), ('ملازم أول', 'ملازم أول'), ('نقيب', 'نقيب'), ('رائد', 'رائد'), ('مقدم', 'مقدم'), ('عقيد', 'عقيد'), ('عميد', 'عميد'), ('لواء', 'لواء'), ('لواء مساعد وزير', 'لواء مساعد وزير')], error_messages={'blank': 'الرجاء إدخال اسم الرتبة.', 'unique': 'هذه الرتبة مسجلة بالفعل.'}, max_length=50, unique=True, verbose_name='الرتبة')),
                ('fee', models.DecimalField(decimal_places=2, default=100.0, error_messages={'invalid': 'الرجاء إدخال قيمة صحيحة.'}, max_digits=10, verbose_name='الرسوم الشهرية')),
            ],
            options={
                'verbose_name': 'رسوم الرتبة',
                'verbose_name_plural': 'رسوم الرتب',
                'ordering': ['id'],
            },
        ),
    ]
