# Generated by Django 5.2 on 2025-08-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_rankfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='system_related',
            field=models.BooleanField(default=False, verbose_name='خاص بالنظام'),
        ),
    ]
