# Generated by Django 5.2 on 2025-08-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_transactiontype_system_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='transaction',
            new_name='financial_record',
        ),
    ]
