# Generated by Django 5.2 on 2025-08-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_rename_transaction_subscription_financial_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
