# Generated by Django 5.2 on 2025-08-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_notes'),
        ('financials', '0009_remove_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(help_text='الرقم التسلسلي للقسط لهذا العميل', verbose_name='رقم القسط')),
                ('due_date', models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح'}, verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, error_messages={'invalid': 'يرجى إدخال قيمة مالية صحيحة'}, max_digits=12, verbose_name='القيمة')),
                ('status', models.CharField(choices=[('مدفوع', 'مدفوع'), ('غير مدفوع', 'غير مدفوع')], default='غير مدفوع', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('paid_at', models.DateField(blank=True, error_messages={'invalid': 'أدخل تاريخ صالح'}, null=True, verbose_name='تاريخ الدفع')),
                ('client', models.ForeignKey(error_messages={'blank': 'يجب تحديد العضو', 'null': 'يجب ربط القسط بعضو'}, on_delete=django.db.models.deletion.RESTRICT, related_name='installments', to='clients.client', verbose_name='العضو')),
                ('financial_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='installments', to='financials.financialrecord', verbose_name='المعاملة المالية')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'الأقساط',
                'ordering': ['client', 'installment_number'],
                'unique_together': {('client', 'installment_number')},
            },
        ),
    ]
