# Generated by Django 5.2 on 2025-08-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_paid_amount_client_subscription_fee'),
        ('financials', '0010_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='client',
            field=models.ForeignKey(error_messages={'blank': 'يجب تحديد العضو', 'null': 'يجب ربط القسط بعضو'}, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='clients.client', verbose_name='العضو'),
        ),
    ]
