# Generated by Django 5.2 on 2025-09-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_alter_installment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_method',
            field=models.CharField(choices=[('نقدي', 'نقدي'), ('إيداع بنكي', 'إيداع بنكي'), ('مصروف بنكي', 'مصروف بنكي'), ('شيك', 'شيك'), ('تحويل بنكي', 'تحويل بنكي')], error_messages={'blank': 'طريقة الدفع مطلوبة', 'invalid_choice': 'يرجى اختيار طريقة دفع صحيحة'}, max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
