# Generated by Django 5.2 on 2025-09-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_client_hire_date_client_residence'),
        ('financials', '0012_alter_financialrecord_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='client',
            field=models.ForeignKey(error_messages={'blank': 'يجب تحديد العضو', 'null': 'يجب ربط القسط بعضو'}, on_delete=django.db.models.deletion.RESTRICT, related_name='installments', to='clients.client', verbose_name='العضو'),
        ),
    ]
