# Generated by Django 5.2 on 2025-09-09 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_alter_installment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='financial_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='financials.financialrecord', verbose_name='المعاملة المالية'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='financial_record',
            field=models.ForeignKey(error_messages={'blank': 'يجب تحديد المعاملة المالية', 'null': 'يجب ربط الاشتراك بمعاملة مالية'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='financials.financialrecord', verbose_name='المعاملة المالية'),
        ),
    ]
