# Generated by Django 5.2 on 2025-09-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_alter_installment_financial_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='financial_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='financials.financialrecord', verbose_name='المعاملة المالية'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='financial_record',
            field=models.OneToOneField(error_messages={'blank': 'يجب تحديد المعاملة المالية', 'null': 'يجب ربط الاشتراك بمعاملة مالية'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='financials.financialrecord', verbose_name='المعاملة المالية'),
        ),
    ]
