# Generated by Django 5.2 on 2025-09-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_alter_installment_financial_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='financial_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment', to='financials.financialrecord', verbose_name='المعاملة المالية'),
        ),
    ]
