# Generated by Django 5.2 on 2025-09-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_client_financial_record_and_more'),
        ('financials', '0016_alter_installment_financial_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, error_messages={'invalid': 'يرجى إدخال قيمة مالية صحيحة'}, max_digits=12, verbose_name='قيمة القرض')),
                ('issued_date', models.DateField(error_messages={'invalid': 'أدخل تاريخ صالح'}, verbose_name='تاريخ إصدار القرض')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('client', models.ForeignKey(error_messages={'blank': 'يجب تحديد العضو', 'null': 'يجب ربط القرض بعضو'}, on_delete=django.db.models.deletion.RESTRICT, related_name='loans', to='clients.client', verbose_name='العضو')),
                ('financial_record', models.OneToOneField(error_messages={'blank': 'يجب تحديد المعاملة المالية', 'null': 'يجب ربط القرض بمعاملة مالية'}, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='financials.financialrecord', verbose_name='المعاملة المالية')),
            ],
            options={
                'verbose_name': 'قرض',
                'verbose_name_plural': 'القروض',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_number', models.PositiveIntegerField(help_text='الرقم التسلسلي للدفعة لهذا القرض', verbose_name='رقم الدفعة')),
                ('due_date', models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح'}, verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, error_messages={'invalid': 'يرجى إدخال قيمة مالية صحيحة'}, max_digits=12, verbose_name='القيمة')),
                ('status', models.CharField(choices=[('مدفوع', 'مدفوع'), ('غير مدفوع', 'غير مدفوع')], default='غير مدفوع', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('paid_at', models.DateField(blank=True, error_messages={'invalid': 'أدخل تاريخ صالح'}, null=True, verbose_name='تاريخ الدفع')),
                ('financial_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayment', to='financials.financialrecord', verbose_name='المعاملة المالية')),
                ('loan', models.ForeignKey(error_messages={'blank': 'يجب تحديد القرض', 'null': 'يجب ربط السداد بقرض'}, on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='financials.loan', verbose_name='القرض')),
            ],
            options={
                'verbose_name': 'سداد',
                'verbose_name_plural': 'السدادات',
                'ordering': ['loan', 'repayment_number'],
                'unique_together': {('loan', 'repayment_number')},
            },
        ),
    ]
