# Generated by Django 5.2 on 2025-10-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0017_loan_repayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='financial_record',
        ),
    ]
