# Generated by Django 5.2 on 2025-10-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0018_remove_subscription_financial_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='financial_record',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='financial_record',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='financial_record',
        ),
    ]
