# Generated by Django 5.2 on 2025-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0019_remove_installment_financial_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='الرصيد'),
        ),
    ]
